name: Deploy page

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-page:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 🧰
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies 🧰
        run: |
          pip install -r requirements.txt

      #Using another action for AsyncAPI for validation
      - name: Validate asyncapi.yml ✅
        uses: WaleedAshraf/asyncapi-github-action@v0.0.9
        with:
          filepath: asyncapi.yml

      #In case you do not want to use defaults, you for example want to use different template
      - name: Generate HTML from asyncapi.yml 📄
        uses: docker://asyncapi/github-action-for-generator:2.1.7
        with:
          template: "@asyncapi/html-template@0.28.1" #In case of template from npm, because of @ it must be in quotes
          filepath: asyncapi.yml
          parameters: baseHref=/YouCube/ sidebarOrganization=byTags #space separated list of key/values
          output: docs/api

      - name: Deploy page 🚀
        run: mkdocs gh-deploy --force
